### ISSUE TITLE
Consider a new config option queryTimeoutMillis?

### ISSUE THREAD

**Issue by ChieveiT** [Vincit/tarn.js#12]
My knex hang infinitely in production. I am still not sure whether it is stucked during query(still working on it, turn on `DEBUG=knex:*` and waiting...). The production network environment is so bad and hard to simulate. It is possible that a connection will dead without any response in the production network (maybe a tcp proxy works wiredly, hold the connection for knex, but never make a new connection to the db after the old one is broken).

I see there is already a timeout function for builder but it would be better if tarn can provide a global timeout option for query.

**Comment by kibertoad** [comment]
@koskimas Would any help be needed for this?

**Comment by elhigu** [comment]
Tarn really cannot know anything about queries. It could provide `maximumLeaseMillis`, which would somehow try to forcefully get back the resource that was borrowed from pool.

However if that kind of method would be used, it would mean that instead of returning the actual resource from pool, tarn.js would have to return some delegate object, which would notice automatically and reject usage of resource who has been forcefully returned to the pool.

Also that kind of global timeout would not affect only queries on knex, but also to transactions, since tarn doesn't know if connection was leased for transaction or for single query.

I don't think that this usecase should be implemented by tarn (though that lease timeout + delegate is kind of interesting concept, but it could/should be implemented as a separate layer on top of tarn to keep tarn as simple and robust as it promises).
