### ISSUE TITLE
consider adding some way to instrument time-to-acquire?

### ISSUE THREAD

**Issue by bttmly** [Vincit/tarn.js#14]
I'd like to be able to see metrics on how long it takes to acquire an object from the pool, which would help us tune our pool configuration over time. If you're open to this I'd be happy to take a stab at a PR. I'm not sure the best implementation strategy, but perhaps an event emitter. Something like the following would be great:

```js
pool.on("acquire", (ms) => {
  metrics.gauge("db_connection_pool", ms);
})

// or, to avoid making pool itself an emitter:

pool.metrics().on("acquire", (ms) => { ... });
```

**Comment by bttmly** [comment]
@elhigu  good point! as long as acquisition requests have some sort of identifier then we can everything else onto the caller:

```js
pool.on("acquireRequest", (id) => { ... })
pool.on("acquireSuccess", (id) => { ... })
pool.on("acquireFail", (id, err) => { ... })
pool.on("release", (id) => { ... })
```

**Comment by elhigu** [comment]
@koskimas do you think it would be fine if I implement these  hooks and if you have any comments on naming?

**Comment by koskimas** [comment]
As long as they are synchronous simple hooks that don't complicate the codebase, I'm fine with them. The suggested names seem fine. The `id` could just be a running integer? I'd like to keep tarn dependecy free.

**Comment by elhigu** [comment]
I was prototyping a bit with this and I figured out that following set of events could be pretty complete:

```
// Adds synchronous event handlers to for example to allow externally
// collecting some diagnostic data of pool behaviour. If any of these
// hooks fail, all errors are catched and warnings logged.

// resource is acquired from pool
pool.on('acquireRequest', eventId => { });
pool.on('acquireSuccess', (eventId, resource) => { });
pool.on('acquireFail', (eventId, err) => { });

// resource returned to pool
pool.on('release', resource => { });

// resource was created and added to the pool
pool.on('createRequest', eventId => { });
pool.on('createSuccess', (eventId, resource) => { });
pool.on('createFail', (eventId, err) => { });

// resource is destroyed and evicted from pool
// resource may or may not be invalid when destroySuccess is called
pool.on('destroyRequest', (eventId, resource) => { });
pool.on('destroySuccess', (eventId, resource) => { }); 

// pool is destroyed (after poolDestroySuccess all event handlers are also cleared)
pool.on('poolDestroyRequest', eventId => { });
pool.on('poolDestroySuccess', eventId => { });

// when internal reaping event clock is activated / deactivated
pool.on('startReaping', () => { });
pool.on('stopReaping', () => { });
```

Most of the events actually cannot have event id passed on by Tarn, because we don't know what id for example returned resource should be passed. So I did select parameters in a way that the user of the pool can store the `eventId` in the related resource if (s)he decides to and keep track when certain resource is actually returned to the pool.

Events when resource is destroyed / evicted is also one that has been requested in knex side and which is pretty hard to recognise any other way so I added that too in the list... so I also ended up to add corresponding create events 😬

Too much? 🤔I'll add work in progress PR in a moment so that you can check out how intrusive that system is.

**Comment by elhigu** [comment]
Work in progress PR https://github.com/Vincit/tarn.js/pull/23 to demonstrate how implementation would look like.

**Comment by elhigu** [comment]
Hook supports will come in next release.
