### ISSUE TITLE
Destroy should expect a Promise

### ISSUE THREAD

**Issue by mfidemraizer** [Vincit/tarn.js#15]
Docs says:

```
  // function that destroys a resource. This is always synchronous
  // as nothing waits for the return value.
  destroy: (someResource) => {
    someResource.cleanup();
  },
```

IMO, this could be a wrong assumption: what if the whole cleanup is asynchronous? For example, `amqplib.close` returns a `Promise`. 

Currently, this means that cleaning-up is fire&forget.

Is is really hard to support `Promise`?

Thank you in advance.

**Comment by koskimas** [comment]
You can do async stuff there. The description is misleading. Tarn just does nothing if the async operation fails. 

What should it do? Return the resource to the pool (nope!!)) Retry delete? How many times? Is the operation retryable?

There are alot of questions to answer. You can implement the retry or whatever action yourself of course.

**Comment by mfidemraizer** [comment]
@koskimas hey ;-)

Ok, but does it expect a `Promise`? Or it's just we may run a fire&forget async operation?

**Comment by elhigu** [comment]
> Ok, but does it expect a `Promise`? Or it's just we may run a fire&forget async operation?

That was already answered above. Reasoning that was given in @koskimas comment would be good to add to the docs so that poeple can understand why  it is irrelevant if we wait destroy to finish or not (we can wait and the do nothing).

If tarn would would emit events about its operations and would allow to catch an event for example when resource is destroyed it would be a different story though.

**Comment by koskimas** [comment]
@elhigu Waiting for the destruction to finish can matter when `pool.destroy()` is called. I only realized it once @alubbe posted the [PR](https://github.com/Vincit/tarn.js/pull/16).

**Comment by elhigu** [comment]
Fixed in https://github.com/Vincit/tarn.js/pull/16 will be included in next release.
