### ISSUE TITLE
Support exponential backoff for create retries

### ISSUE THREAD

**Issue by oxc** [Vincit/tarn.js#65]
When create fails, it would be nice if we could exponentially increase the retry interval, and reset it to the original value once a resource was sucessfully created (or linearily decrease with each sucessfully created resource).

I have quickly implemented this in a custom subclass like this:

```ts
class ExponentialBackoffLinearDecreasePool<T> extends Pool<T> {
  constructor(opt: PoolOptions<T>) {
    super(opt);
    const baseCreateRetryIntervalMillis = this.createRetryIntervalMillis;
    this.on('createFail', () => {
      if (this.createRetryIntervalMillis === this.createTimeoutMillis) return;
      this.createRetryIntervalMillis = Math.min(this.createRetryIntervalMillis * 2, this.createTimeoutMillis);
      this.log(`Increased createRetryIntervalMillis to ${this.createRetryIntervalMillis}`, 'debug' as any);
    });
    this.on('createSuccess', () => {
      if (this.createRetryIntervalMillis === baseCreateRetryIntervalMillis) return;
      this.createRetryIntervalMillis = Math.max(this.createRetryIntervalMillis - baseCreateRetryIntervalMillis, baseCreateRetryIntervalMillis);
      this.log(`Decreased createRetryIntervalMillis to ${this.createRetryIntervalMillis}`, 'debug' as any);
    });
  }
}
``` 

Perhaps something like this could be integrated?

**Comment by elhigu** [comment]
I don't think it is generally a good idea since it is very opinionated logic. If we would like to offer a way to change retry logic, it should allow to override the whole check algorithm if the failed create operation should be automatically retried.

Also I don't think that retry functionality even should be in tarn.js, since it hides the error (for example connection error) until retry count runs out and easily will cause application to hang for a long time because of that. 

Use cases for it are pretty rare... maybe it could make sense in an environment, where it is very common that create fails, but then it gets back online in couple of seconds.

**Comment by oxc** [comment]
Fair enough, thanks!
