### ISSUE TITLE
Exemple use cases

### ISSUE THREAD

**Issue by Shuunen** [Vincit/tarn.js#71]
Hi there, 

As a total noob in the node pooling world, it would be great to see some simple exemple use cases,

Either in a folder on this repo, or online on codesandbox.io / stackblitz.com / codepen.io like websites

Thanks

**Comment by elhigu** [comment]
In tests there are lots of examples how this works, but also PRs for example use cases are welcome.

**Comment by Shuunen** [comment]
@elhigu the actual unique test file contains 2400 lines of code, that's "lots of examples" like you said, still not equivalent to a simple exemple use case in my opinion

Sure PRs for example are welcome... but as this issue imply, examples exists to help newcomers understand what a library do,
If I don't understand the purpose of a library, I will not spend time digging in source code or tests files to finally make a fork and contribute some exemples

I'm not critisizing the lack of exemples on this repo, just suggesting to the contributors that if they want to grow a bigger community, some easy to understand exemples will help

**Comment by kibertoad** [comment]
This is a fairly niche library, mostly aimed at use-cases such as database connection pools. What is the use-case that you are thinking of?

**Comment by Shuunen** [comment]
> use-cases such as database connection pools

Oh alright, thanks

> What is the use-case that you are thinking of?

I'm not thinking about any use-case in specific, because I don't understand the purpose of the library.
The use-case you provided is helpful to understand what is possible to do with this lib.

> This is a fairly niche library

I get that now...

**Comment by elhigu** [comment]
> I'm not critisizing the lack of exemples on this repo, just suggesting to the contributors that if they want to grow a bigger community, some easy to understand exemples will help

Growing bigger is not a goal for this library. It is mainly written for knex, since there was no other pool library that we could trust not giving strange problems and get new features in if really necessary. We tried all the usual ones before writing our own.

> I'm not thinking about any use-case in specific, because I don't understand the purpose of the library.
The use-case you provided is helpful to understand what is possible to do with this lib.

I suppose one would need to first study concept what is pool and from there at least for me it has been pretty straightforward do see from pool APIs what features they support. 

It is not very common that developers need explicit pool in their apps, usually pools comes integrated in other libraries which are directed more to a app developers instead of library developers.

Anyhow as I mentioned PRs for example usecase are welcome.
